version: '2.1'
services:
  corpus-platform:
    image: docker-reg.ecovacs.com/library/corpus-platform:20191126-047bd41
    container_name: corpus-platform
    ports:
      - "8080:8080"
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    entrypoint:
      - sh
      - -c
      - go run server.go
    volumes:
      - /etc/localtime:/etc/localtime