version: '2.1'
services:
  corpus-platform:
    image: docker-reg.ecovacs.com/library/corpus-platform:20191126-bb597b5
    container_name: corpus-platform
    ports:
      - "8080:8080"
    restart: always
    logging:
      options:
        max-size: "5M"
        max-file: "10"
      driver: json-file
    environment:
      - SERVER_PORT=8080
      - MONGO_HOST=10.89.100.14
      - MONGO_PORT=27017
      - MONGO_DBNAME=corpus
    volumes:
      - /etc/localtime:/etc/localtime